### ISSUE TITLE
Program spamming Tempo set at 413793 at second 0.00!

### ISSUE THREAD

**Issue by Seredusc** [RedInquisitive/Midi-Factorio#1]
I was just using the program after I chose if the tracks were percussion and how much they were offset it just started spamming tempo set at 413793 at second 0.00! The attachment doesn't support midi files so I am giving you a link were you can download it. http://kylelandry.com/wp-content/uploads/Skyrim-Main-Theme.mid

**Comment by RedTopper** [comment]
Good choice in song, I'm interested to get this working. Let me check it out!

**Comment by RedTopper** [comment]
Unfortunately, that specific MIDI seems to break Java's internal MIDI parser (it doesn't detect any notes).
No idea why!

But this MIDI works great: http://midicollection.net/songs/index.php?id=18!

I shifted the bass line up 12 steps (track 2) and switched the track from piano to bass in game. Go ahead and try that one!

This technically isn't a solution to the problem, but it is enough to get you Skyrim in Factorio.

**Comment by Seredusc** [comment]
Thank you so much!
 It is incredible how epic this I can play stuff on my piano then actually get it into factorio epic coding skills cheers!

**Comment by RedTopper** [comment]
I'll close this, but also leave a note in the readme about broken MIDIs. Thanks!
