### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Ristellise** [RedInquisitive/Midi-Factorio#2]
Is it possible to make each midi track be seperate?

Also another thing is that i would like the speakers to be so called plug and play. and when creating the blueprint make an option to not include the speakers. This would help in mod compatibility. (In the future i might plan for a mod for the midi spectrum.)

**Comment by RedTopper** [comment]
> Is it possible to make each midi track be seperate?

I'm not quite sure what you mean by this... Each track is separate already. Unless you are talking about channels, witch would get complicated VERY fast unfortunately. 

> and when creating the blueprint make an option to not include the speakers

Ok

**Comment by Ristellise** [comment]
ah i see i was talking about channels :P

**Comment by Ristellise** [comment]
um sorry to bump but this midi when imported into factorio lags the game to less than 1 FPS https://onlinesequencer.net/73973

**Comment by RedTopper** [comment]
err, how many combinators was that song? I understand why.... I'm surprised it even exported!

It's likely you will have to edit the song manually to get that to import into Factorio, considering the piano part looks like [this](https://gyazo.com/60b6d66eb74b35dbe3fa45ddd58466a3) in music notation software...

**Comment by Ristellise** [comment]
i need to check again XD
